---
title: "EC 421"
subtitle: "Pre-Quiz"
author: "Edward Rubin"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    seal: false
---
class: clear

.center.b.mono[Economics 421 Pre-Quiz]

<br>
.b.mono[Name (first and last):] .pink.b.mono[Pre-Quiz Key]

.b.mono[Instructions] Complete this short quiz to the best of your ability. Points will be given for effort. Extra-credit points are available for higher scores. You may leave class after you complete the quiz.

.b.mono[Important] Don't worry if you cannot give a perfect answer. Give your best effort. No phones, calculators, or outside materials. .it[Any] cheating could earn you a zero in this class.

<br>
.b.mono[01\.] Define the term "variance."

.pink[
.b.mono[Answer] Variance tells us about a random variable's dispersion/variability/deviation (relative to its mean). Alternative: variance is one way to know how much a variable changes. Mathematically:
$$
\begin{align}
  \mathop{\text{Var}} \left( X \right) = \mathop{E}\left[ (X - \mu_X)^2 \right]
\end{align}
$$
where $\mu_X$ is the mean of $X$, _i.e._, $\mathop{E}\left[ X \right]$.]

<br>
.b.mono[02\.] For the equation $\text{Crime}_{i} = \alpha + \beta \, \text{Police}_{i} + u_i$, if the number of police officers (given by $\text{Police}$) increases by 1 unit, how much do we expect crime (given by $\text{Crime}$) to change?

.pink[
.b.mono[Answer] Based upon the equation, for each 1-unit increase in *police*, we expect a $\beta$-unit increase in *crime*.]

<br>
.b.mono[03\.] Imagine we are testing the null hypothesis H.sub[o] $\mu = 3$ against the alternative hypothesis H.sub[a] $\mu \neq 3$. If the p-value is 0.001, what should we conclude?

.pink[
.b.mono[Answer] With a p-value below 0.05 (0.001 < 0.05), we reject the null hypothesis (H.sub[o] $\mu = 3$) and state that there is statistically significant evidence (at the 5-percent level) that H.sub[a] is true—_i.e._, that $\mu$ is not 3.]

<br>
.b.mono[04\.] For the estimated regression model $\hat{y}_{i} = 1.3 + 5.4 x_{i}$, interpret the intercept.

.pink[
.b.mono[Answer] The intercept tells us our expected value for the variable $y$ when the variable $x$ is equal to zero. Thus, when $x_i=0$, we expect $y_i$ will be 1.3.]

<br>
.b.mono[05\.] Define the concept of the .it[median].

.pink[
.b.mono[Answer] The median is the value "in the middle" of a distribution—meaning it has the same number of observations above and below it.]

<br>
.b.mono[06\.] What does the notation $\mathop{E}\left[ X \right]$ mean?

.pink[
.b.mono[Answer] $\mathop{E}\left[ X \right]$ is notation for "the expected value of $X$", which is the *mean* of the random variable $X$.]

---
class: clear

<br>
.b.mono[07\.] For $\log\left(Q_i\right) = 12 + 0.8 \log \left( P_i \right) + u_i$, interpret the slope. .it[Note:] $P$ denotes price, and $Q$ refers to quantity.

.pink[
.b.mono[Answer] For the "log-log" model, our slope term denotes an elasticity. Thus, for a 1% increase in price, we expect a 0.8% increase in quantity.
]

<br>
.b.mono[08\.] Define the concept of a .it[mean].

.pink[.b.mono[Answer] The *mean* gives us the expected outcome (or average outcome) for a distribution—also thought of as its center. If we repeatedly draw from a distribution, the average outcome will be the mean.]

<br>
.b.mono[09\.] Define the term "standard error."

.pink[.b.mono[Answer] "Standard error" refers to the standard deviation of the distribution for an estimator (_e.g._, our linear-regression estimator).]

<br>
.b.mono[10\.] Answer each of the next three questions as honestly as possible. Use only 1–2 sentences per answer.

.move-right[.b[A.] What do you hope to get out off this class?]

<br><br><br><br><br>

.move-right[.b[B.] Why are you an economics major (or whichever major you've chosen)?]

<br><br><br><br><br><br>

.move-right[.b[C.] Why do you want a college degree?]
